### ISSUE TITLE
Set up to work on my laptop to catch up with classes

### ISSUE THREAD

**Issue by monihueb** [Introduction-to-Programming-FH/IPFH-2223#2]
Hi,
I have been trying to set up our workspace/porgram at home on my laptop, but I am having difficulties.

How to install jupyter notebook so I can read the classes?
So far I installed pyCharm, even the professional version. All I read online is something else ....
Best 
Moni

**Comment by br0ast** [comment]
When you enter Pycharm and start a new project, can you open a Windows terminal and then write `pip install jupyter`?
